server:
  servlet:
    session:
      timeout: 30m
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot-mybatis?serverTimezone=Asia/Shanghai
    username: root
    password: root
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5

# mybatis配置
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:/aufffth/entity/*.xml

